### ISSUE TITLE
Gw2Specialization: Add Tier to onTraitClick

### ISSUE THREAD

**Issue by discretize** [madou/armory-component-ui#16]
`<Gw2Specialization
          id={56}
          activeTraits={[2177, 2061, 2138]}
          onTraitClick={id => doSomething(id)}
        />`

Currently you only get the `id` of the clicked trait.
With the tier level (0, 1, 2) one could actually do something useful with the id information (e.g. user-selectable traits).

The `layoutTraits` in `Specialization` probably needs to receive the tier level for major traits. Didn't dive too deep though

**Comment by keirbhaltair** [comment]
I added that callback parameter with the exact intention of selecting a trait, for a project I took an unexpectedly long break from and that I plan to return to the first weekend after I finish watching Breaking Bad...

Anyway, getting the ID is enough, you can look the rest up [in the API](https://api.guildwars2.com/v2/traits/2177) or in the provided redux store.

**Comment by discretize** [comment]
Cool, getting it via the store works indeed! ..if your project was to create a build editor, you're welcome to join us over at discretize :)

**Comment by keirbhaltair** [comment]
I am making a build database, originally driven by the very fact that neither qT, dT nor MetaBattle are good for open world builds. I don't really think that a guild such as dT would want to focus on such resources, I don't even intend to have golem DPS as a required field, so for the time being thanks for the offer but I'll probably just continue with my project. \^\^ It's just that I've been a lot busy and a bit lazy for a longer while than intended, but I plan to get back to it very soon.
