### ISSUE TITLE
Using this lib in 2020 with latest react

### ISSUE THREAD

**Issue by leobouilloux** [madou/armory-component-ui#25]
Hello,

I tried to use your library with the last react version in date (16.13.1) and the project is not running correctly. I got the following error when I try to render your sample in my project:
```
Failed to compile.

./node_modules/armory-component-ui/armory-component-ui.js
Module not found: Can't resolve 'axios' in '/Users/leo/mhenlo/node_modules/armory-component-ui'
```

I created a new app using this command:
```shell
npx create-react-app my-app
```
I installed your lib as described in your documentation:
```shell
npm install armory-component-ui --save
```
Here is my App.js file:
```js
import React from 'react'

import { Provider } from 'react-redux';
import { combineReducers, applyMiddleware, createStore } from 'redux';
import thunk from 'redux-thunk';
import { reducers, Tooltip } from 'armory-component-ui';

const store = createStore(
  // Create the root reducer.
  combineReducers(reducers),

  // Set the thunk middleware.
  applyMiddleware(thunk),
);

const App = () => (
  <Provider store={store}>
    <span>
      <div>My Other Components Here</div>
      <Tooltip />
    </span>
  </Provider>
);

export default App
```

I'm not sure that you are still working on this, but cheers for all your work, it's really insane!

**Comment by itsdouges** [comment]
hey dude! yeah im not working on it much but definitely contributions are welcome!

looks like you need to also install peer dependencies

```
 "peerDependencies": {
    "axios": "^0.16.x",
    "classnames": "^2.x.x",
    "function-batch": "^1.1.x",
    "i18n-react": "^0.3.x",
    "lodash": "^4.x.x",
    "lz-string": "^1.4.4",
    "react": ">=15",
    "react-debounce-decorator": "^0.1.x",
    "react-redux": ">=5",
    "reselect": ">=3"
  },
```

if you install those it should fix it - we should probably change them to be dependencies TBH but i'm open for suggestions :D

**Comment by leobouilloux** [comment]
Wow, wasn't expecting an answer, thank you very much! I'll try this afternoon and close if it works :)

**Comment by leobouilloux** [comment]
Okay, I finally got your project running fine.

After adding your package to my project, I moved the dependencies from `peerDependencies` to `dependencies` as you suggested.

 I can create a pull request if you want :)

Thank you again and have a nice weekend.
