### ISSUE TITLE
Add onTraitClicked callback to the Gw2Specialization component

### ISSUE THREAD

**Issue by keirbhaltair** [madou/armory-component-ui#8]
While many of the icon+tooltip components show a single entity, where it is possible to capture a click event over the entire component and know the ID of the underlying skill/trait/item, the Gw2Specialization component shows multiple different entities with separate icons and tooltips.

In order to allow more dynamic usage of the components without having to rely on the component's inner DOM tree, it would be great if the component could send information about click events back to its parent. One option could be adding a function `onTraitClicked` to the Gw2Specialization props, which would be called with the corresponding trait ID whenever its icon would be clicked.

Bonus points for allowing us to change the cursor while hovering over the clickable traits (either automatically if the callback function is supplied, or via a custom class prop that would be applied to the trait's `div`s).

**Comment by madou** [comment]
hey @keirbhaltair, want to try your hand at this issue?

im happy for a `onTraitClicked` to be added, as well as allowing to pass down a `traitClassName` too.

**Comment by keirbhaltair** [comment]
I might try it when I'll have the time, but since I still know very little about React, it might feature some amount of arm flailing... \^\^

**Comment by keirbhaltair** [comment]
Thanks for the assistance! I tried it out in my Angular project now and it seems to work perfectly. ^^
